name: Lint (frontend)
on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Cache node packages
        uses: actions/cache@v4
        env:
          cache-name: cache-node_modules
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('frontend/pnpm-lock.yaml') }}

      - name: Install node packages
        run: make pre-ui

      - name: Validate UI
        run: make ui-validate
